version: '3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    # container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASS: ${WP_PASS}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PW: ${WP_ADMIN_PW}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    image: wordpress
    # container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/
    networks:
      - inception
    restart: always
    expose:
      - "9000"
  
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    # container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-data:/var/www/
    restart: always

volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/chaejkim/data/wordpress

  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/chaejkim/data/mariadb


networks:
  inception:
    driver: bridge 
